name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttgf26a
        with:
          pdk: gf180mcuD

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttgf26a

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: install verilator
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y git autoconf flex bison make g++ libfl-dev zlib1g-dev
          git clone https://github.com/verilator/verilator
          cd verilator
          git checkout v5.036
          autoconf
          ./configure
          make -j$(nproc)
          sudo make install

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@ttgf26a

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@ttgf26a
